Feature/user info
holololro/15GG_front pull request #14
Opened 2022-09-29 08:51 UTC by 7ngenious

2022-09-29 08:56 UTC, luciancah commented on src/components/userInfo/styles/gameCard.s.tsx
> +  margin-top: 4px;
마진 실제로 4px 되게 수정해주세용

2022-09-29 08:57 UTC, therealjamesjung requested changes

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/gameAnalysis/components/Summoner.tsx
> +  item0: string;
items로 해서 string[] 로 해줘용

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/gameAnalysis/components/Summoner.tsx
> +  item0,
마찬가지

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/gameAnalysis/components/TeamInfoContainer.tsx
> +            item0={'3133'}
마찬가지

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/gameAnalysis/components/TeamInfoContainer.tsx
> +            item0={'3033'}
마찬가지

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/userInfo/UserRank.tsx
> +  const {
이거 state로 바꾸면서 API랑 변수명 인터페이스 사용해서 맞춰주기

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/userInfo/UserStatInfo.tsx
> +  const {
마찬가지 API변수랑 인터페이스 맞추고 변수명 맞추고

2022-09-29 08:57 UTC, therealjamesjung commented on src/components/utility/Url.tsx
> +const FULLURL = 'http://ddragon.leagueoflegends.com/cdn/12.18.1/img';
이거 변수명들 아까 바꾼대로 안됐음

2022-09-29 22:09 UTC, 7ngenious commented on src/components/userInfo/styles/gameCard.s.tsx
> +  margin-top: 4px;
수정완료했습니다

2022-09-29 22:10 UTC, 7ngenious commented on src/components/gameAnalysis/components/Summoner.tsx
> +  item0: string;
수정완료했습니다

2022-09-29 22:10 UTC, 7ngenious commented on src/components/gameAnalysis/components/Summoner.tsx
> +  item0,
수정완료했습니다

2022-09-29 22:10 UTC, 7ngenious commented on src/components/gameAnalysis/components/TeamInfoContainer.tsx
> +            item0={'3133'}
수정완료했습니다

2022-09-29 22:10 UTC, 7ngenious commented on src/components/gameAnalysis/components/TeamInfoContainer.tsx
> +            item0={'3033'}
수정완료했습니다

2022-09-29 22:10 UTC, 7ngenious commented on src/components/utility/Url.tsx
> +const FULLURL = 'http://ddragon.leagueoflegends.com/cdn/12.18.1/img';
수정완료했습니다

2022-10-01 17:18 UTC, merged

2022-10-01 17:37 UTC, 7ngenious commented on src/components/userInfo/UserRank.tsx
> +  const {
현재는 userinfo폴더 내 index파일에서 두 인터페이스에 대해 state가 되어 있습니다. 참고 부탁드립니다

2022-10-01 17:38 UTC, 7ngenious commented on src/components/userInfo/UserStatInfo.tsx
> +  const {
규칙을 참고하여 단축을 지우고 앞에 붙이는 형식으로 바꿨습니다